version: '3.8'
services:
  db:
    build:
      context: ./mysql
    ports:
      - "3306:3306"
    env_file:
      - ./.env/db.env
    volumes:
      - mysql_data:/var/lib/mysql
  api:
    build:
      context: .
    command: /bin/sh -c "rm -f ./tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
      - "1234:1234"
    env_file:
      - ./.env/api.env
    volumes:
      - .:/sample_api:cached
      - bundle:/usr/local/bundle
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  mysql_data:
  bundle:
